### ISSUE TITLE
Detection on android device

### ISSUE THREAD

**Issue by marwakhalil** [Apercu/react-native-zeroconf#41]
Hello, 
First of all thanks for this library, 
I Manage to discover advertised services from my mac when running react-native-zeroconf from my iPhone or from the iOS simulator, but i detect nothing from android device 
is there any special thing that i should add to android project to make it work
Thanks,

**Comment by Apercu** [comment]
Hey,

No I don't believe so, did you made sure you have installed the gradle dependencies? I believe since the feature from @gcmartins93 we need tinydnssd, but that should be it

**Comment by marwakhalil** [comment]
Hey @Apercu , 
I believe you talk about the tinydnssd that is already added in the react-native-zeroconf gradle file through `compile 'com.youview:tinydnssd:1.2.7'` 
the problem is i still got nothing in android, testing on my iPhone, i detect the service instantly, it's like magic, but on android, scan is started, and it's like forever, i detect nothing ... 
i don't know what should i do about this maybe @gcmartins93  knows a something about this  ...

**Comment by michbil** [comment]
I can confirm Android build is broken now. I updated to the latest library version, and detection on android stopped working. I tried debugging, and can see that application hangs indefinetely at MDNSDiscover.resolve line
```
 protected void resolve(String serviceName) {
        WritableMap service = new WritableNativeMap(); // this line is called

        try {
            MDNSDiscover.Result serviceResult = MDNSDiscover.resolve(serviceName, RESOLVE_TIMEOUT); // << waits indefinetely at this line

```

**Comment by michbil** [comment]
Switched to 0.7.1 for now, it works just fine

**Comment by Apercu** [comment]
Arf, sorry for the inconvenience. The addition from @gcmartins93 seem to be the issue. Gabriel, can you please advice regarding the error?

**Comment by marwakhalil** [comment]
Hey, i've tried with 0.7.1 and still not working on android, it's like not detecting anything :(

**Comment by michbil** [comment]
@marwakhalil double check your build, make sure you relinked and rebuilt your app. 0.7.1 is completeley functional

**Comment by marwakhalil** [comment]
@michbil i've checked all, the app is functional and there no errors still got my ActivityIndicator animating in the scanning phase with no detection, on the other hand, the iOS app works great, instantly detection and resolving for the service , i even add the `compile 'com.youview:tinydnssd:1.2.7'` dependency for the reac-native-zeroconf gradle manually because i didn't find it in  V 0.7.1

**Comment by Apercu** [comment]
The `0.8.0` introduced this new dependency that's why you don't see it. Like @michbil said you need to double check the build and that there is nothing cached on your project that could cause this.

**Comment by gcmartins93** [comment]
Hey guys, I'm going to review the code later today. Since I have a production app, using the latest version of this package and working fine (both Android and iOS), I don't know right now what may be causing this issue.

Thanks for reporting, anyway.

**Comment by michbil** [comment]
Android 7.0

**Comment by marwakhalil** [comment]
Android 6.0

**Comment by merindorium** [comment]
Hi, @Apercu.
The problem is in `com.youview:tinydnssd:1.2.7` package. `RESOLVE_TIMEOUT` is 0, that why we somehow getting stuck in `while` loop of `resolve` method without timeout exception.
The only solution I have now is to set `RESOLVE_TIMEOUT` to non-zero and resolve service again on timeout exception.

**Comment by gcmartins93** [comment]
According to Tinydnssd documentation, when timeout param is set to zero, it'll listen forever for packets. The way this package is originally implemented, there is no way to pass _timeout_ param down to native modules. So, it's up to the user to manage timeout via js code - by stoping service when timeout and starting it again when required. It's up to you guys, to decide if this kind of timeout management to be handled by the module or by the user itself.

**Comment by gcmartins93** [comment]
Sorry, my bad, what @merindorium said makes sense. The service resolution is hanging forever, not discovering. I'll change timeout to a non-zero value and create an exception manager for timeout case, as suggested.

**Comment by marwakhalil** [comment]
@gcmartins93 thanks for the changes, unfortunately, this is not resolving the service it was lasting forever resolving and with the new branch that you made, every time i resolve i got this message after a while "An error Occurred  Resolving service failed with message: Timeout"

**Comment by michbil** [comment]
@gcmartins93 Hi, tried your build. Still not working. Seems like RESOLVE_TIMEOUT is not the issue. I debugged your code, it just catches SocketTimeoutException timeoutException two times and gives up.

**Comment by merindorium** [comment]
Hi, I tried this build too and it works fine for me. I used 1000ms timeout and 5 attempts.

**Comment by gcmartins93** [comment]
Service resolution is what tinydnssd is in charge of, and we rely on it to do that, but, to you guys, it's failing. We can change RESOLVE_TIMEOUT and MAX_ATTEMPTS_TO_RESOLVE constants to achieve a better result, by testing a better combination, as @merindorium did. @marwakhalil, if the service couldn't be resolved on timeout interval, u'll receive this message, it's the expected behavior. 
What are we supposed to do when a service cannot be resolve, try again indefinitely or just for a number of times? 

If you are trying to resolve your own service, I'd recommend to register your service in a different protocol than http, maybe your own protocol, to avoid resolving unnecessary services.

**Comment by marwakhalil** [comment]
Actually i understand that when we can't resolve a service we need to try again every time
i've tried what @merindorium said and 've changed both  RESOLVE_TIMEOUT and MAX_ATTEMPTS_TO_RESOLVE but still not resolving,
Infact, using the 0.7.1 version i manage to detect and resolve the service except for the txtRecord that's some kind of my problem now

**Comment by gcmartins93** [comment]
Folks, do you agree with indefinitely attempts or should it give up when a certain threshold is reached?

**Comment by marwakhalil** [comment]
it should give up of course after a time of course ...

**Comment by marwakhalil** [comment]
Hi Guys, 
I found out a something, 
actually @gcmartins93 thanks for the updates that u made on your branche and what i was really missing is the records, Let me explain TinyDNSSD does not work when your service does not have all the records, for example an A-Record is missing the TinyDNSSD does not work and show a TimeOutException (as it is in my case), unfortunately the getAttributes() that exists in NsdServiceInfo.java is still hidden even in the current version of my android (6.0), i don't know for the higher versions, but i finally detected and resolved services from RN app using [https://github.com/Appetiza/react-native-zeroconf/tree/release](thisBranch) but after advertising a service with its full records 
for example i use dns-sd with this command : `dns-sd -P "MyTestwebpage" _http._tcp local 80 page.com page.com path=/path-to-page.html ["key"]="hello this is my page"` and that's how there won't be a TimeOutException in resolution a service and it's Resolved !! 
Thanks

**Comment by sandeepmistry** [comment]
I'm experiencing a similar issue, with Wireshark I tracked the problem down to the `tinydnssd` library sending out the resolve request on a random port (non-5353): https://github.com/youviewtv/tinydnssd/blob/master/lib/src/main/java/com/youview/tinydnssd/MDNSDiscover.java#L151-L185

The device I'm trying to discover receives the request, but responds on the multicast IP but with a port of 5353.

**Comment by gcmartins93** [comment]
@sandeepmistry, tinydnssd creates a socket on a [random free port ](https://github.com/youviewtv/tinydnssd/blob/5e672903d6fe7890fcc23f67f8ac7f18eeb24bc6/lib/src/main/java/com/youview/tinydnssd/MDNSDiscover.java#L154), as you said, but, it always send the datagram package to [5353 port](https://github.com/youviewtv/tinydnssd/blob/5e672903d6fe7890fcc23f67f8ac7f18eeb24bc6/lib/src/main/java/com/youview/tinydnssd/MDNSDiscover.java#L159).

Can't you respond to the same port the requestor use instead of hard coding port 5353?

@Apercu, since there is no agreement about how should tinydnssd handle timeout, I'm gonna to pull request @merindorium suggestion of 1000ms timeout and 5 attempts. Are your okay with it?

**Comment by Apercu** [comment]
Yep sounds good, I think it will be better than the current state

**Comment by ianjwood** [comment]
I"m having a similar/familiar experience with Android; when I first started to look at Zeroconf everything worked fine. (react-native version 0.47.1 zeroconf version 0.8.1, on a range of different devices - both simulator and real).

Something suddenly stopped working and I can't figure out what. I do get an updated callback which logs the contents of a call to getServices() but this just outputs {} :/

I've tried putting breakpoints in various places - all of the callbacks in the DiscoveryListener as well as scan etc. sendEvent only gets called for the start (and stop - at the point it's intended to!).

Everything is working perfectly on iOS :)

**Comment by josomers** [comment]
What is the status on Android mDNS detection please?

**Comment by ianjwood** [comment]
@josomers the issue I had turned out to be Android build related; I'm not entirely sure what happened but a clean and an Invalidate Cache/Restart in Android studio fixed it.

**Comment by josomers** [comment]
@ianjwood It didn't resolve the problem. Actually I don't see how this could even resolve it. I'll try to debug the library a bit.

**Comment by josomers** [comment]
Is there a specific reason not to use the nsdManager.resolve (native Android)?
When I try to use that, I get the following resolved results:

name: ArtSoundAP, type: ._artSoundA._tcp, host: /192.168.10.135, port: 5000, txtRecord: manufacturer=ArtSound

**Comment by Apercu** [comment]
@gcmartins93 So apparently txtRecords should be grabbable using mdns, do you think we should revert the tinydnssd implementation since it appears to cause quite a lot of issues to people?

**Comment by merindorium** [comment]
I've found that [empty TXT record issue](https://issuetracker.google.com/issues/37020436) was fixed in Android >= 7. 
For previous versions you still need to use 3rd party libraries.

**Comment by Apercu** [comment]
Given that the txt issue linked by @merindorium has been fixed in newer Android versions, issue that motivated the tinydnssd implementation, I've decided to revert the specific commit and publish a new version `0.8.2`.

Please everyone try using that one instead, and reopen the issue if the problem persists.

I would still want to thank @gcmartins93 for the work he provided into getting a temporary solution that worked on previous Android versions for some people.

**Comment by fivepointseven** [comment]
Just tried 0.8.2 on Android 7, service is resolved, but no txt record is present

**Comment by alexborisov** [comment]
I'm still getting this issue. I'm on 0.8.3 running on S8 Android 7.0. I get `found` and `update` events fine, but I never get `resolved`. In any case all i get for `getServices()` is an array of devices objects and they only have a `name` key.

**Comment by mi-mazouz** [comment]
still have this issue with the last version!
